version: '3.8'
services:
  app:
    image: prometheus_sample:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
